name: Run Postman Tests with Newman

on:
  push:
    branches: [ "main" ] 

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 

      - name: Install Newman
        run: npm install newman newman-reporter-htmlextra

      - name: Run Newman Tests
        run: ./node_modules/.bin/newman run dummyjson.postman_collection.json -e dummyjson.postman_environment.json -r htmlextra --reporter-htmlextra-export report.html
        continue-on-error: true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report 
          path: report.html 
